const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
const POST_TRANSACTION = 'POST_TRANSACTION';
const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
const TRANSACTION_ERROR = 'TRANSACTION_ERROR';

export {
  GET_TRANSACTIONS,
  POST_TRANSACTION,
  DELETE_TRANSACTION,
  TRANSACTION_ERROR,
};
